#!/usr/bin/env bash

set -e

# ndk abi to rust target
current_target() {
  arch=$(adb shell getprop ro.product.cpu.abi)
  case $arch in
  x86)
    target=i686
    ;;
  x86_64)
    target=x86_64
    ;;
  arm64-v8a)
    target=aarch64
    ;;
  armeabi-v7a)
    target=armv7
    ;;
  esac
  echo $target
}

run() {
  local target=$(current_target)
  local profile=${1:-dev}

  export RUSTFLAGS="-Clink-args=-Wl,-rpath,\$ORIGIN"

  cargo ndk -t $target-linux-android --bindgen build --profile $profile

  if [[ $profile == dev ]];then
    profile=debug
  fi

  du -sh ../target/$target-linux-android/$profile/*.so
  adb push ../target/$target-linux-android/$profile/libdevtool.so /data/local/tmp/libgamebot.so
  adb shell am force-stop gamebot.host
  adb shell am start -n gamebot.host/.MainActivity
}

dev() {
  cargo watch -w . -w ../gamebot -s "$0 run $@"
}

"$@"
