#!/usr/bin/env bash

run() {
  set -e
  arch=$(adb shell getprop ro.product.cpu.abi)
  case $arch in
  x86)
    target=i686
    ;;
  x86_64)
    target=x86_64
    ;;
  arm64-v8a)
    target=aarch64
    ;;
  armeabi-v7a)
    target=armv7
    ;;
  esac

  # export ORT_LIB_LOCATION=$HOME/bin/onnxruntime/build/Android
  # export ORT_LIB_LOCATION=$HOME/bin/onnxruntime/build/Android
  # export ORT_LIB_LOCATION=/home/bilabila/bin/onnxruntime/build/Android/Release/java/android/x86
  # export ORT_LIB_LOCATION=$HOME/bin/onnxruntime/build/Android/Release/

  export RUSTFLAGS="-Clink-args=-Wl,-rpath,\$ORIGIN"

  cargo ndk -t $target-linux-android --bindgen build --release

  du -sh ../target/$target-linux-android/release/*.so
  adb push ../target/$target-linux-android/release/libdevtool.so /data/local/tmp/libgamebot.so
  adb shell am force-stop gamebot.host
  adb shell am start -n gamebot.host/.MainActivity
}
dev() {
  cargo watch -w . -w ../gamebot -s "$0 run"
}

"$@"
