[host]
min_version = "0.0.1"

[guest.devtool]
repo = "https://github.com/tkkcc/gamebot_devtool_release"
desc = "debug server for gamebot"

[guest.gallery]
repo = "https://github.com/tkkcc/gamebot_gallery_release"
desc = "what you can do with gamebot"
