[package]
name = "ort-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = { workspace = true }
cached-path = { workspace = true }
dirs = { workspace = true }
hex-literal = { workspace = true }

[features]
# static-link = []
# dynamic-link = []
# vulkan = []
