[package]
name = "ncnn-sys"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
cached-path = "0.6.1"
dirs = "5.0.1"
hex-literal = "0.4.1"

[features]
static-link = []
dynamic-link = []
vulkan = []
