[package]
name = "ncnn"
version = "0.1.0"
edition = "2021"

[dependencies]
ncnn-sys = { workspace = true }
anyhow = { workspace = true }
libc = { workspace = true }

[features]
static-link = ["ncnn-sys/static-link"]
dynamic-link = ["ncnn-sys/dynamic-link"]
vulkan = ["ncnn-sys/vulkan"]
