[package]
name = "ncnn"
version = "0.1.0"
edition = "2021"

[dependencies]
ncnn-sys = { workspace = true}
anyhow = "1.0.89"
libc = "0.2.159"

[features]
static-link = ["ncnn-sys/static-link"]
dynamic-link = ["ncnn-sys/dynamic-link"]
vulkan = ["ncnn-sys/vulkan"]
